name: 'CI/CD Pipeline'

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl shellcheck

      - name: Run linter
        run: |
          shellcheck jc

  release:
    runs-on: ubuntu-latest
    needs: lint
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Archive release files
        run: |
          tar -czf jc-${{ github.ref_name }}.tar.gz ./jc
          zip -r jc-${{ github.ref_name }}.zip ./jc

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          preserve_order: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          make_latest: true
          files: |
            ./jc-${{ github.ref_name }}.tar.gz
            ./jc-${{ github.ref_name }}.zip
